# Pre-commit configuration for code quality and consistency
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: commit-msg
        stages: [commit-msg]
      - id: commit-msg
        stages: [commit-msg]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest before push
        entry: pytest --maxfail=1 --disable-warnings -q
        language: system
        stages: [pre-push]
