version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=pollarize_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
      - DJANGO_SECRET_KEY=your-secret-key-change-this
      - DJANGO_DEBUG=0
      - USE_REDIS=1
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
    volumes:
      - ./staticfiles:/app/staticfiles

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=pollarize_db
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l info
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=pollarize_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
      - DJANGO_SECRET_KEY=your-secret-key-change-this
      - USE_REDIS=1
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A config beat -l info
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=pollarize_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
      - DJANGO_SECRET_KEY=your-secret-key-change-this
      - USE_REDIS=1
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  mysql_data:
