# Generated by Django 5.0.7 on 2025-08-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_user_referral_code_userprofile'),
        ('core', '0002_category_userprofile'),
    ]

    operations = [
    ]
