# Generated by Django 5.0.7 on 2025-08-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0004_alter_bookmark_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_polls', models.IntegerField(default=0)),
                ('active_polls', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('new_votes', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('top_countries', models.JSONField(default=list)),
                ('country_distribution', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['snapshot_type', 'timestamp'], name='analytics_a_snapsho_b31af6_idx'), models.Index(fields=['timestamp'], name='analytics_a_timesta_9a251c_idx')],
                'unique_together': {('snapshot_type', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('poll_view', 'Poll Viewed'), ('poll_vote', 'Poll Vote'), ('poll_share', 'Poll Shared'), ('poll_bookmark', 'Poll Bookmarked'), ('user_register', 'User Registration'), ('user_login', 'User Login'), ('payment_made', 'Payment Made'), ('export_data', 'Data Export')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='polls.poll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx'), models.Index(fields=['user', 'event_type'], name='analytics_a_user_id_7df679_idx'), models.Index(fields=['poll', 'event_type'], name='analytics_a_poll_id_70cdb8_idx'), models.Index(fields=['country_code', 'created_at'], name='analytics_a_country_b689c7_idx'), models.Index(fields=['device_type', 'created_at'], name='analytics_a_device__c313f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PollAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('unique_voters', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('avg_time_spent', models.FloatField(default=0.0)),
                ('bookmark_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('votes_by_country', models.JSONField(default=dict)),
                ('top_countries', models.JSONField(default=list)),
                ('votes_by_hour', models.JSONField(default=dict)),
                ('votes_by_day', models.JSONField(default=dict)),
                ('votes_by_platform', models.JSONField(default=dict)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_revenue_per_vote', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('view_to_vote_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='polls.poll')),
            ],
            options={
                'verbose_name': 'Poll Analytics',
                'verbose_name_plural': 'Poll Analytics',
                'indexes': [models.Index(fields=['poll'], name='analytics_p_poll_id_6afa2b_idx'), models.Index(fields=['last_updated'], name='analytics_p_last_up_a1468e_idx'), models.Index(fields=['total_votes'], name='analytics_p_total_v_e4e31d_idx'), models.Index(fields=['completion_rate'], name='analytics_p_complet_d57c5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polls_created', models.IntegerField(default=0)),
                ('active_polls', models.IntegerField(default=0)),
                ('total_poll_views', models.IntegerField(default=0)),
                ('polls_voted', models.IntegerField(default=0)),
                ('total_votes_made', models.IntegerField(default=0)),
                ('total_votes_received', models.IntegerField(default=0)),
                ('bookmarks_made', models.IntegerField(default=0)),
                ('shares_made', models.IntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('most_active_hour', models.IntegerField(default=12)),
                ('most_active_day', models.IntegerField(default=1)),
                ('primary_country', models.CharField(blank=True, max_length=2)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
                'indexes': [models.Index(fields=['user'], name='analytics_u_user_id_a24cf9_idx'), models.Index(fields=['total_revenue'], name='analytics_u_total_r_ea791a_idx'), models.Index(fields=['polls_created'], name='analytics_u_polls_c_d93c54_idx')],
            },
        ),
    ]
