# Generated by Django 5.0.7 on 2025-08-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="is_public",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
