# Generated by Django 4.2.23 on 2025-08-10 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_category_user_referral_code_userprofile'),
        ('polls', '0002_alter_poll_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('reddit', 'Reddit'), ('other', 'Other')], max_length=20)),
                ('referral_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='poll',
            name='allows_revote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='core.category'),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='vote_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='votesession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votesession',
            name='votes_available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['is_active', 'is_public'], name='polls_poll_is_acti_f52b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['creator', 'created_at'], name='polls_poll_creator_ea8c83_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['category', 'is_active'], name='polls_poll_categor_7c36d6_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['is_paid', 'vote_price'], name='polls_poll_is_paid_3dbab7_idx'),
        ),
        migrations.AddIndex(
            model_name='votesession',
            index=models.Index(fields=['user', 'poll'], name='polls_votes_user_id_846a55_idx'),
        ),
        migrations.AddField(
            model_name='pollshare',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='polls.poll'),
        ),
        migrations.AddField(
            model_name='pollshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='polls.poll'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pollshare',
            index=models.Index(fields=['referral_code'], name='polls_polls_referra_f4c7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='pollshare',
            index=models.Index(fields=['user', 'shared_at'], name='polls_polls_user_id_89ce19_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'created_at'], name='polls_bookm_user_id_5d2821_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'poll')},
        ),
    ]
