# Generated by Django 4.2.23 on 2025-08-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_bookmark_pollshare_alter_poll_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
    ]
